### PR TITLE
include correct assembly

### PR DESCRIPTION
**Pull request by earloc**

### CODE REVIEW

**Comment by xavier-morera** [comment]
Done, added to develop. @gjunge will start preparing a new release with the changes that are there right now. 

I still have the pending to test SolrCloud with the people that need this, but they moved it to priority 2.

**Comment by earloc** [comment]
glad to help ;).

Any hints on an ETA for this, yet?

**Comment by xavier-morera** [comment]
I merged it on to develop last night, I will release in a day or two. Currently on the road in a conference. Thanks @earloc

**Comment by earloc** [comment]
Sounds good for me!

And thx for all your effort!

**Comment by earloc** [comment]
The missing Packages are both netstandard2.0 / are using the newer csproj-Format / Toolchain.

Do you know how AppVeyor generates the nuget-packages?

I had an issue a while ago packaging netstandard-libs with nuget.exe; had to update nuget.exe in order to successfully generate the package.
->
https://github.com/NuGet/Home/issues/4491

Maybe the same happens in your AppVeyor Environment?

Could successfully generate a package for the nuspec with nuget.exe 4.3.0.4406

**Comment by earloc** [comment]
a possible workaround would be to create the package via "dotnet pack" instead of nuget.exe, if that is an option in AppVeyor. But for that to work as intended (by utilizing the nuspec) there would be another change needed in the respective csproj-files:
https://github.com/dotnet/cli/issues/2170

**Comment by xavier-morera** [comment]
I created 0.7.1 using nuget and was able to create both. I will investigate further as I prefer to get AppVeyor set up correctly and get this automated first.

**Comment by gjunge** [comment]
It seems that there are 2 packages with the same name:
image

The thing that netstandard 2.0 packages don't work seems unlikely, since the Microsoft.DependencyInjection.SolrNet is a netstandard 2.0 package and it's NuGet package gets created.

It seems that SolrNet , which is now SolrNet.Core doesn't create the right package name (SolrNet.Core), and this conflicts with the CommonServiceLocator.SolrNet project, which create the  `SolrNet` package. 
One can see in the build log that 9 packages are created, but only 8 artifacts exist.

Since I'm on holidays I have no access to an IDE to fix this.

**Comment by earloc** [comment]
Hmm, that seems to be a point.

Nevertheless, the generated package for _Microsoft.DependencyInjection.SolrNet_ doesn´t seem to be correct (Version 1.0.0?) - and shouldn´t the package be named _SolrNet.Microsoft.DependencyInjection_?. looks like it´s grabbing metadata from csproj instead of nuspec.

Would be interesting to know how AppVeyor creates the packages...from the screenshot above i would suspect it utilizes "dotnet pack".

**Comment by gjunge** [comment]
Perhaps AppVeyor changed something, it used to work just fine in my build. 

So we can perhaps conclude so far that the netstandard projects ignore the name given in the nuspec file (perhaps not even using the nuspec file?) and that is why a) SolrNet.Core is not being published and b) SolrNet.Microsoft.DependencyInjection has the wrong name and version. 
It does seem totally plausible that AppVeyor started using `dotnet pack` and this caused a breaking change in our build. 
If possible, could somebody update the csproj file of those two projects to see if that does he trick?

**Comment by earloc** [comment]
plz have a look at #318 , was able to locally build both packages via dotnet pack with theses modifications

**Comment by xavier-morera** [comment]
Ok, I am in Strata in NY, as soon as I get back to hotel will take a look. Thanks @earloc !

**Comment by xavier-morera** [comment]
@earloc your rock. That helped

image

Thanks @gjunge too

**Comment by gjunge** [comment]
Great!

**Comment by earloc** [comment]
Looks good, my colleague @benuto just confirmed that the package now contains the right assemblies. 
Can be closed from my perspective!
Thx @xavier-morera and @gjunge

**Comment by xavier-morera** [comment]
Thanks to you @earloc for implementing the fix

**Pull request merged**
