### PR TITLE
Solr cloud support draft version

### PR DESCRIPTION
**Pull request by dkrupnou**
Draft version of solr cloud support with tests

### CODE REVIEW

**Comment by andmos** [comment]
Oooh this is nice. Today I use Zookeeper.net directly to do this...

**Comment by ny6asik** [comment]
andmos,
You no need to do this manually now, this pull request contains SolrCloudStateProvider, which encapsulates all work with zookeeper using Zokeeper.Net library.

**Comment by mausch** [comment]
Could you clarify what's the relation (if any) between this and https://github.com/mausch/SolrNet/compare/master...vladen:master ?

**Comment by dkrupnou** [comment]
Sure. Vladlen and I are in the same team who develops this functionallity

**Comment by janhoy** [comment]
Since @mausch has so little bandwidth, it would benefit this project is you could select a few of the people who have been most active contributors and give them commit karma on this project. Then SolrNET would probably get a boost in activity and would live on... Just a suggestion?

**Comment by xavier-morera** [comment]
I have pulled into solrcloud branch for testing in my project and will review the work. Apologies for being slow, trying to catch up.

cc: @dkrupnou / @AlexeyKozhemiakin

**Comment by xavier-morera** [comment]
Continued in SolrCloud branch

**Pull request closed without merging**
