### PR TITLE
added SimpleInjector support

### PR DESCRIPTION
**Pull request by jrmartins**
- added module to support Simple Injector

### CODE REVIEW

**Comment by gjunge** [comment]
@jrmartins  thanks for the PR! I'm currently on holidays, I will review it at the end of the month.

**Comment by gjunge** [comment]
Could you please also add an entry for the new DI in the /README.md file and basic usage in /documentation/Initialization.md?

**Comment by jrmartins** [comment]
Sure.
What do you usually do regarding the Nuget package? Do you create one when ready to merge or should I create and publish one?

**Comment by xmorera** [comment]
@jrmartins I take care of the Nuget package. Just let me know once it is ready.

**Comment by jrmartins** [comment]
@xmorera All done.

**Comment by gjunge** [comment]
Excellent! Thank you!

**Comment by jrmartins** [comment]
Great. Thanks.
Just a quick heads up, I added a link to the Nuget package in the documentation, assuming that the package would follow the naming convention of the other packages.
The package is not yet available or has a different name. Would it be worth to remove link in the meantime?

**Pull request merged**
