### PR TITLE
Update StructureMap.SolrIntegration to .net standard2.0

### PR DESCRIPTION
**Pull request by CiprianMo**
Updated StructureMap.SolrIntegration to .net standard2.0
Setting up cores from configuration using System.Configuration has been changed because .config files are not gonna be used anymore in .net core apps. Now configurations should be taken from a json file.

### CODE REVIEW

**Comment by gjunge** [comment]
Great work @ciprianmo . I will review the PR after the weekend, what I saw briefly looks good. 
However, and this is a question which also interests @xavier-morera , this implementation contains a breaking change, namely all those that use the old .config way (not sure if there are those that do so) will have to change their code. 
How much work would it be to have a conditional compilation here? So include System.Configuration only for net46 and have exclude any classes dealing with config from he netstandard dll (this can be done in csproj)?

Again thanks for the good work!

FYI, ninject integration deals with the exact same issue.

**Comment by CiprianMo** [comment]
I don't think it will be too much work, I will try to make different implementation of this for net462 and core.

**Comment by xavier-morera** [comment]
Thanks @CiprianMo 

Regarding @gjunge 's comment,  indeed the best way to go is to avoid breaking changes as much as possible, make it easier for people to upgrade. If @CiprianMo can include the change, it will be much better.

**Comment by gjunge** [comment]
@CiprianMo  Let me know if you want/need any help.

Referencing #372

**Comment by CiprianMo** [comment]
I think I know what I have to do there, it's just that on weekends I'm a little busier, but tomorrow afternoon I will submit the changes... :)

**Comment by CiprianMo** [comment]
@gjunge I made so that the tests target net 462 and net core2.0, and all the tests pass for me.

If you accept this pull request, I could update ninject as well

**Comment by CiprianMo** [comment]
Oh yea, that's right. I will try to implement your idea @gjunge  and see how that turns out. 

Thanks for the feedback  !

**Comment by gjunge** [comment]
Thanks @ciprianmo for taking your time on this one, really appreciated!

**Comment by CiprianMo** [comment]
@gjunge no problem at all, I'm actually learning a lot here, so the benefits are mutual, and thanks for your patience. 

So I wasn't able to implement your ideas entirely, because  "SolrServerElement" has to inherit from "ConfigurationElement" and multiple inheritance is not possible in c#. Also having a partial class for SolrNetRegistery doesn't seem to be needed here, in my opinion, I can just have another constructor that is only included for NET46 version. 

I also added a few separate test for NET46 only. Let me know what you think of the  code I submitted now.

**Comment by CiprianMo** [comment]
@gjunge yesterday the commit i made was a bit messy, I made a clean up now. Sorry for delays and so many commits

**Comment by gjunge** [comment]
@CiprianMo No worries. I won't have time to go over it today, hopefully tomorrow I can review.

**Comment by gjunge** [comment]
Hi @CiprianMo , I posted a PR to your branch, could you have a look? 
https://github.com/CiprianMo/SolrNet/pull/1

**Comment by gjunge** [comment]
Thanks @CiprianMo for the contribution! Much appreciated.

**Pull request merged**
