### PR TITLE
upgrade Unity 5.0.0

### PR DESCRIPTION
**Pull request by JeroenvdBurg**
Upgrade to unity 5.0
included EnterpriseLibrary Common for the Guard class

### CODE REVIEW

**Comment by gjunge** [comment]
Fixes #364

**Comment by gjunge** [comment]
@JeroenvdBurg  Thanks, looks great!

**Comment by JeroenvdBurg** [comment]
Thanks, my first contribution :-) 

Will try to update to Unity 5.5.5 in the next change, however there are a lot of serious breaking changes which I need to fix then.

**Comment by gjunge** [comment]
@JeroenvdBurg any help is super appreciated!
Do note that your fix is currently in the develop branch, and will be released in the 1.0.1 version.
So if you continue developing on it, you should branch of the develop branch, until it is merged into the master branch.
I will let you know when that happens.

**Comment by JeroenvdBurg** [comment]
Allright, that is clear. Thanks.

**Comment by xavier-morera** [comment]
@gjunge can we do 1.0.1? Good time to change to fork and pull too, now that you mentioned develop branch.

@JeroenvdBurg thank you!

**Comment by gjunge** [comment]
@xavier-morera 
We just have to update the version number on the relevant packages and create a PR from the branch where I created the new contribution guide.

**Comment by xavier-morera** [comment]
@gjunge 

Cool, I will do it. Just wanted to know if you believed it is ready to go.

**Comment by gjunge** [comment]
@xavier-morera let's just wait for #368 to be finished.

**Comment by gjunge** [comment]
@xavier-morera 
Regarding versioning, do we update all projects to version 1.0.1, or only the affected ones? 
Pro: one repo, one changelog, one version
Con: I shouldn't have to update my NuGet package if my project didn't change.

**Comment by xavier-morera** [comment]
@gjunge that was the question, let's wait for #368 

Regarding versioning, I believe all projects to 1.0.1 makes more sense.

I know it is not "nice" to have to update to a new version where my library has no changes, but it is more confusing having different versions and keeping track of dependencies.

**Comment by gjunge** [comment]
@xavier-morera Didn't notice #368 until yesterday . 

So I'll update all to 1.0.1 once #368  is in .

**Pull request merged**
