### PR TITLE
Add facet ranges to solr query result

### PR DESCRIPTION
**Pull request by hamedsabzian**
use for get sparsity of record on any facet with a gap.
http://wiki.apache.org/solr/SimpleFacetParameters#Facet_by_Range

### CODE REVIEW

**Comment by jondarrer** [comment]
@mausch Do you need any help merging these facet range integrations?

**Comment by philwilks** [comment]
Is there any reason why it can't be merged? With Solr 6.2.1 it's no longer possible to use facet dates, so facet ranges are needed.

**Comment by gjunge** [comment]
@xavier-morera  , do you have an ETA when you will come to this pull request?

**Comment by xavier-morera** [comment]
Hi,

I am working first on upgrading to newer versions of .Net which I expect will take a few weeks. This includes Ninject and Autofac

Xavier

--------------------------------------------

**Comment by xavier-morera** [comment]
Merged to develop on https://github.com/SolrNet/SolrNet/pull/309

Targeted for version 0.8.1

@hamedsabzian @TLogik @jondarrer @philwilks would you have a minute to test with develop branch?

Thanks to @gjunge

**Pull request closed without merging**
