### PR TITLE
Release version 1.0.1 from Develop

### PR DESCRIPTION
**Pull request by gjunge**
Last time we release from the develop branch. After this we move over to the Fork and Pull workflow. 
Our contribution guide has been updated.

### CODE REVIEW

**Comment by xavier-morera** [comment]
Thanks @gjunge 

Last time with Gitflow Workflow, moving to Fork and Pull workflow

**Comment by xavier-morera** [comment]
@gjunge I made a change on the id of CommonServiceLocator.SolrNet as it had only SolrNet, my intention to avoid confusion. However when I deployed to NuGet I get an error message specifying CommonServiceLocator is a reserved namespace. Should we just change to SolrNet.CommonServiceLocator instead?

**Comment by gjunge** [comment]
@xavier-morera I left it SolrNet  on purpose, in order to provide backwards compatibility.

* Once upon a time the CommonServiceLocator dependency injection was part of SolrNet. So everybody who would get SolrNet would also get that dependency injection
* We've split it of into it's own package, because in those days CommonServiceLocator was not netstandard compliant, and it didn't seem it was ever going to be. However we wanted SolrNet to be netstandard compliant. 
* So in order not to break the setup of all those people using SolrNet as packagereference, and using the CommonServiceLocator as DI, I've made the SolrNet project `SolrNet.Core` in NuGet (since nobody really should use that one without another DI package), and made  the CommonServiceLocator.SolrNet the `SolrNet` package in NuGet.
* Confusing , a little for us package maintainers, but helpful for new users (grab SolrNet and one can use it straight away), and not breaking for existing users (we moved the cheese internally, not externally).

**Comment by xavier-morera** [comment]
@gjunge I should have asked. I made a mistake, Sorry. I’ll fix it.

**Comment by xavier-morera** [comment]
@gjunge release is complete. 1.0.1 published to NuGet.

**Pull request merged**
