### PR TITLE
Remove unused items from Solution

### PR DESCRIPTION
**Pull request by gjunge**
Removed items that are not in use anymore in order to make the solution cleaner and thus easier for other contributors to start with.
#290

### CODE REVIEW

**Comment by xavier-morera** [comment]
@gjunge Can you please take a look at the conflict in the csproj?

**Comment by gjunge** [comment]
@xavier-morera No problem.

**Comment by gjunge** [comment]
@xavier-morera merged and added the changelog.

I think that after this one, it might be a good time to create release 0.7.1 .

If you need help publishing to NuGet, let me know.

**Comment by xavier-morera** [comment]
@gjunge I will create it. Is SolrCloud something you can take a look? There is a branch with a pull request from some developers that I think are from Rackspace: https://github.com/SolrNet/SolrNet/tree/solrcloud

 This might be key for getting to Solr 6.x, in case you have a chance. If you can't, don't worry.

**Comment by gjunge** [comment]
I created a new issue for SolrCloud (which I don't reference here, in order not link it to this PR)

Personally I've never user SolrCloud, we're doing the sharding ourselves, but I can certainly help with big parts of the issue.

**Pull request merged**
