### PR TITLE
Fixes #406

### LINKED ISSUE #406: Add an option to prevent MappingManager to use the DeclaringType instead of the ReflectedType
Hi, 

Seems like a bug to us. We do not want the declaring type of the property we add for the mapping, but its reflected type instead. We took a version of MappingManager.cs and removed all occurrences of "property.DeclaringType" when the code gets the type of the PropertyInfo instance. 

Please a support to prevent the MappingManager to use the DeclaringType. 

Thanks

### PR DESCRIPTION
**Pull request by DaveWut**
You can now specify to force the usage of the reflected type when adding a property mapping.

### CODE REVIEW

**Comment by gjunge** [comment]
Thanks for the PR. 
I’ll review it in the coming days, have to wrap my head around it since I haven’t visited this area of the project that much. 
In the meantime would  you be able to add one or two unit tests that test and show the use case?

Thanks again!

**Comment by DaveWut** [comment]
Hi, 

I will make the appropriate unit tests this week-end. I will notify you here once this is done (and anyway, I think Github will do it).

Thanks

**Comment by DaveWut** [comment]
Hey @gjunge I can't compile the solution. Have you any documentation how to setup my PC in order to be able to compile? I use Visual Studio 2017 Enterprise. VS seems unable to detect target .NET Framework 4.6 or NETStandard 2.0 even if all target framework are already installed on my system.

**Comment by DaveWut** [comment]
I found a way to build using the VS's Developer Command Prompt. I found out on the internet that multi targeting projects are not yet perfectly supported or at least working with Visual Studio. Please tell me otherwise if I'm wrong. 

So yeah, I was finally able to add a unit test related to my change. If you think more are needed, please tell me.

**Comment by gjunge** [comment]
@DaveWut Make sure you have the latest updates for VS 2017. Indeed in the first version it wasn't supported that well, but now everything works fine. I've the solution on three separate PCs, some VS Enterprise, some VS Community Edition, and all work fine.

I'll check your PR now.

**Comment by gjunge** [comment]
And thanks a million for taking the time and effort to contribute!

**Comment by DaveWut** [comment]
My pleasure for helping! 

I made a second modification and both unit tests should now reflects what the purpose of the change is. It seems that .GetFields(Type type) did not returned what I expected.

**Comment by gjunge** [comment]
@DaveWut just got back from a short trip abroad, I will have a look at it today or tomorrow.

**Comment by gjunge** [comment]
Great, the tests explain the use case nicely.

**Pull request merged**
