### PR TITLE
Async support

### PR DESCRIPTION
**Pull request by gjunge**
* Added Async support to main interfaces and their implementations:
   * ISolrConnection (SolrConnection, SolrPostConnection)
   * ISolrCommand (CommitCommand, AddCommand, DeleteCommand etc)
   * ISolrOperations, ISolrBasicOperations  (SolrServer)
* Added Integration tests.
* Asyncing ISolrCoreAdmin has NOT been done yet. I think there needs to be some refactoring there anyway to bring it up to date with Solr 6-7.

### CODE REVIEW

**Comment by xavier-morera** [comment]
Thanks again, @gjunge

**Comment by gjunge** [comment]
@xavier-morera Are your builds failing, mine are passing and creating the NuGet packages: https://ci.appveyor.com/project/gjunge/solrnet/build/0.7.1.43

Let me know if there is anything specific I can help with. 
For now I continued with cleaning up the solution a bit more, removing all obsolete files, and getting the other packages (structuremap , nhibernate etc) to their latest version. I expect next week to push this.  

I also toyed around with getting SolrNet to target both .net 4.6 and Netstandard 2_0 and that went surprisingly smooth. The only issue is that AppVeyor doesn't run sdk2.0 yet, so the build fails. I'll return to that branch (and perhaps add the new MS dependency injection) at a later stage.

**Comment by xavier-morera** [comment]
@gjunge I am running into something weird. Can you please do a clean and rebuild all? I just downloaded your [branch](https://github.com/gjunge/SolrNet/blob/async-support/SolrNet/Impl/SolrConnection.cs) and in SolrConnection.cs when I do a rebuild I get this in PrepareGetWebRequest: 

image

**Comment by gjunge** [comment]
My master branch is not up to date. 

What you see on the left side of the screenshot is up to date, and you see there the new Value Tuple (see https://blogs.msdn.microsoft.com/mazhou/2017/05/26/c-7-series-part-1-value-tuples/). It seems it is not recognized by VS.
Did all the NuGet packages get restored? What version of VS are you running?

**Comment by xavier-morera** [comment]
Let me give it a shot.

**Comment by xavier-morera** [comment]
@gjunge build works now, thanks.

**Comment by xavier-morera** [comment]
@gjunge Just give me a couple of days to test this version with my application and then I will release

**Comment by gjunge** [comment]
@xavier-morera Excellent. I'll continue cleanup (which doesn't affect the actual production code).

Once we got this build out of the door it would maybe be a good idea to have a beta version published to NuGet, either from the dev or from the release branch, so that other people can easily help us test, and whoever wants, can always run the latest version. 
I assume this could be automated in appveyor, that whenever a build succeeds in the develop branch, a NuGet package is published.

**Comment by gjunge** [comment]
@xavier-morera Thanks, after using the project for so long it is time to give back. 

In the meantime I'm steaming ahead. With every PR I make sure that my CI's pass and keep in mind not to break anything for current users. 

If after merging a PR another PR has conflicts, leave it aside, leave me  a comment and I'll rebase and recreate the Pull Request. 

I still have netstandard 2.0 support underway, which also keeps support for net 4.6 , but also includes support for the new Microsoft Dependency Injection so it will be super easy to use SolrNet in AspNetCore (running on whatever platform). 
I still have some open items there but I expect to finish tomorrow or Wednesday. 

After that I'll go on with creating a docker script to run SOLR locally, so later on we will be able to get rid of the SOLR inside the repository.

**Comment by gjunge** [comment]
And btw, totally understand you have deadlines to keep and are disconnected from the project. Currently I am able to give that extra push and let me know if/where I can fill.

**Comment by xavier-morera** [comment]
Thanks @gjunge

**Pull request merged**
