### PR TITLE
Upgrade project to .NET version 4.6

### PR DESCRIPTION
**Pull request by gjunge**

### CODE REVIEW

**Comment by gjunge** [comment]
I think we are ready to merge this back into the master?

**Comment by xavier-morera** [comment]
@gjunge I just removed SampleSolrApp and updated build. Would you have a few minutes to confirm it looks good?

https://github.com/SolrNet/SolrNet/tree/net-update-plus-autofac-ninject

**Comment by gjunge** [comment]
@xavier-morera Checked the SampleSolrApp   seperation. 
I added some changes to both SolrNet (#291) and the new SolrNetSamples repo.
I would also like if both #292 and #293  could be merged. This would give a great basis to continue development.

**Comment by xavier-morera** [comment]
Before merging into master I need to create a release branch and then will merge. We are using Gitflow workflow.

**Pull request merged**
