### PR TITLE
Adding collations support

### PR DESCRIPTION
**Pull request by ariasjose**
Adding collations support.
Removing collation property as it is not part of the Solr response format.

### CODE REVIEW

**Comment by gjunge** [comment]
@ariasjose  Thanks for your contribution, great to see you left that backward compatibility in place.

**Comment by ariasjose** [comment]
Thanks @gjunge for taking your time and incorporating the changes.

**Comment by gjunge** [comment]
@ariasjose  Thanks for contributing!

It's now in our develop branch, it will be part of our 1.0.0 release.

Could you have a peak at #310 , it is in the area of what you did, perhaps you can give a quick insight.
Some work was done to fix this bug (https://github.com/SolrNet/SolrNet/tree/collation-parsing-issue-310?files=1), but that is already not compatible with the changes you made.

**Comment by ariasjose** [comment]
Thanks for letting know of that scenario as I didn't contemplated it.
I'll take a look at it and incorporate proper changes to support it.

**Comment by ariasjose** [comment]
When pellcheck.collateExtendedResults=false it seems like only collation queries are shown with out hits and corrections fields. 

Solr 5.x +
```xml
<lst name="collations">
  <str name="collation">audit differences</str>
  <str name="collation">(au dot) differences</str>
   ...
</lst>
```
Solr 4.x -
```xml
<str name="collation">audit collation</str>
<str name="collation">(aod it) collation</str>
...
```
To keep it simple In case 4.x- version is used hits will have -1 and corrections will be an empty collection in CollectionResult class. Also I'll add the corresponding test cases.

```c#
public class CollationResult {
        public string CollationQuery { get; set;}
        public long Hits { get; set;}
        public IDictionary<string, string> MisspellingsAndCorrections { get; set;}
    }
```
Thoughts?

**Comment by gjunge** [comment]
Thanks for the analysis! 
The only thing I feel not too happy about is the -1 of the hits property. The correct way would be to make the hits property Nullable, but this would make working with it so much more a pain. 
Another option is throwing an InvalidOperationException when somebody tries to get the Hits when collateExtendedResults is set to false. The exception can explain that getting hits is not supported when that property  is false. 
What are your thoughts?
In the end keeping it -1 is also an acceptable way.

**Comment by ariasjose** [comment]
I agree, working with Nullables has its drawbacks. I like the idea of throwing an exception when collateExtendedResults=false and somebody tries to get the Hits property value. Also I'm making these properties internal for set accessors so user doesn't have the ability of changing them.

Let me know if you agree on the same.

**Comment by gjunge** [comment]
Yep, also agree. Thanks for helping!

**Comment by ariasjose** [comment]
You're welcome!
I have created pull request #355 with those changes.
Please take a look.
Thanks

**Pull request merged**
