### PR TITLE
Add support for ConstantScore query

### PR DESCRIPTION
**Pull request by gjunge**
Implements #324

### CODE REVIEW

**Comment by xavier-morera** [comment]
Thank you @gjunge for both. 

Comment and question: At this point no one besides the original implementers of the SolrCloud branch have been able to test, however they have been using it in production for a while as they noted. Maybe it can be included in this release and we get then people to test?

What do you think?

**Comment by gjunge** [comment]
@xavier-morera  I think it is save to do so, since it is kind of an "opt-in thing" isn't it. Meaning it will not break anything else.

And if we do so, what do you think of "resetting" our versioning. Going to 1.0.0, and then doing semantic versioning. Because:
* the project is 8 years old, so being beta is not relevant
* the x.x.1 doesn't mean anything.
* let's be standard
* etc.

And I guess we should stop changing versions of projects that don't change (all these DI integration projects that automatically get their version bumped). As a consumer of these projects I would expect something new to come out everytime a version gets changed, but that doesn't happen, it's mostly only the Solr.Core project that gets changed, and I, as a consumer, can update that one independently (once we remove the square brackets from the nuspec file).

**Comment by xavier-morera** [comment]
@gjunge Agreed on all points. The versions of SolrNet have always been a bit odd for me, however out of respect of the original creator I did not intervene. I believe at this point we could think of doing something like what happened with Solr in 2011 where it [jumped from 1.4 to 3.1](https://wiki.apache.org/solr/Solr3.1) to match Lucene. Therefore we could have SolrNet 7.0 and know it is compatible with Solr 7.0. 

I know there is a lot of functionality that will not yet be available but having a more standard versioning as you mention can help make it clearer for consumers. And yes, a DI version upgrade should not be a version change, instead we could guide ourselves by Solr versionining.

Thoughts?

**Comment by gjunge** [comment]
@xavier-morera I've been thinking about this on and off for the last days, since it doesn't feel right to match the version of SolrNet with the version of Solr, here are some of my thoughts:

- SolrNet is in general compatible with all version of Solr (Solr 7.0 introduced a breaking change, but the fix we applied was again compatible with all the older version). 
- SolrNet doesn't implement all the features of all the versions.
- Features we add, are often features that have already existed in older features of Solr. So we don't add features to SolrNet 7.0 but to all of SolrNet.
- Our release cycle is not the same as the Solr release cycle (in general Solr and Lucene do have the same cycle)

I propose code-wise to continue the way we are going:
- Maximum compatibility, marking old Solr stuff (like the DateRangeFacet) as Obsolete()
- Decide if/when we remove Obsolete Solr features from our code base (the older NuGets will still be available)

Versioning:
- Bugfixes, increment patch number: 1.0.**X**
- When adding features, add minor version 1.**X**.0
- When removing obsolete features, increment major version **2**.0.0

NuGet:
- Specify in the description what SOLR versions are supported, something like:

> SolrNet is a .NET Open Source client for Apache Solr. This version of SolrNet is compatible with Solr 1.x to Solr 7.x.

Github:
- Change the default ./readme.md with ./documentation/readme.md 
I don't think JetBrains still sponsors anybody for SolrNet?
image

- Update https://github.com/SolrNet/SolrNet/blob/master/Documentation/README.md with supported Solr versions.
- At a later stage might add a matrix which SolrNet removed support for what Solr version. (ie. if you use Solr 2.x , then use SolrNet 1.4, because SolrNet 2.0 removed support for Solr 2.x)

What do you think?

**Comment by xavier-morera** [comment]
Continued discussion on the issue referenced above

**Pull request merged**
