### PR TITLE
Hotfix/solrcloudcore nuget

### PR DESCRIPTION
**Pull request by gjunge**
Hotfix to fix issue #361 

Should also be merged to develop branch.
 
Since it is a nuget fix, it will just create the correct nuget file, no need to bump any version (the version I changed in this code is the csproj version, just for the correctness of it all).

### CODE REVIEW

**Comment by xavier-morera** [comment]
Thanks @gjunge 

Will push to NuGet and merge to develop

**Comment by xavier-morera** [comment]
@gjunge Something went wrong, will work on it in the evening.

**Comment by gjunge** [comment]
@xavier-morera can I help with something?

**Comment by xavier-morera** [comment]
@gjunge I merged into develop and I get this error. Do you have a minute to take a look? Please?

C:\Program Files\dotnet\sdk\2.1.2\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(204,5): error : Could not find a part of the path 'C:\projects\solrnet-crl26\SolrNet.Cloud\lib\net46'. [C:\projects\solrnet-crl26\SolrNet.Cloud\SolrNet.Cloud.csproj]

**Comment by gjunge** [comment]
@xavier-morera  Fixed, works on my build https://ci.appveyor.com/project/gjunge/solrnet-ragxo

**Comment by xavier-morera** [comment]
Excellent @gjunge thanks.

I pushed to NuGet, now SolrNet.Cloud.Core is there

**Pull request merged**
