### PR TITLE
support for facet_ranges while parsing the results

### PR DESCRIPTION
**Pull request by SriLho**
i have found the latest solr 6.6.0 seems to return ranges as facet_ranges for date times. And, also it seems that it is taking the input query string slightly differently too particularly at facet.dates (where the new one seems to be facet.ranges).

I have attempted fixing both the input query string and the result parsing with the new formats. If that is of any help, please pull this in.

### CODE REVIEW

**Comment by xavier-morera** [comment]
Thanks @SriLho I have a question, does this break compatibility with older versions of Solr?

**Comment by SriLho** [comment]
I am not an expert in Solr. Pretty sure it would break the old versions if the code was working well with old branches. I would let you decide what is the best way to deal with it. If you let me know how you want to handle it, I can update the code and give you the updated pull to pick from.

**Comment by xavier-morera** [comment]
Merged to develop on https://github.com/SolrNet/SolrNet/pull/309

Targeted for version 0.8.1

**Comment by xavier-morera** [comment]
Thanks @SriLho for your pull request

**Pull request closed without merging**
