### PR TITLE
Revert "Upgrade project to .NET version 4.6"

### PR DESCRIPTION
**Pull request by xavier-morera**
Reverts SolrNet/SolrNet#286

### CODE REVIEW

**Comment by xavier-morera** [comment]
Need to do release branch first

**Comment by gjunge** [comment]
@xavier-morera  
Not sure what the status is now. 

Although I read on the master branch that there was a  `Merge branch 'release-0.6.1.1001'
image

And I see in the branches page that the release-0.6.1.1001 branch is 4 commits behind
image

Yet the code in the master is behind:
image
image

I assume this has to do with the fact that `Revert "Upgrade project to .NET version 4.6` was done on the master branch, thus making it look that the "old" version of the files is actually the "new" version.

**Comment by xavier-morera** [comment]
@gjunge I made a mistake yesterday and need to fix it.

**Comment by xavier-morera** [comment]
@gjunge I believe I just fixed it. I wanted to include all changes to .Net libraries to 4.6 but exclude XUnit. Can you please take a quick look and let me know if it is correct now? Thank you

**Comment by gjunge** [comment]
@xavier-morera  Checking right now.

**Comment by gjunge** [comment]
@xavier-morera  Looks good now.

Branch wise, what is the "roadmap"?

- The convert-unit-tests-xunit branch will be merge into Develop?
- I have an async branch waiting to be merged (is currently based on the xunit branch, so very up to date), were will I merge it to?
- NuGet: are you going to make nuspec files? Otherwise I can make them, I branch from Develop?


As a side note:
At work we are using tfs 2017/git . In the beginning we were using GitFlow, but backed off, because we found that the "pull request" is really interfering with the tidiness of it all. Once you PR from Dev into Master, Master will be one ahead of Dev due to it having the "Pull Request". So one can rebase, which is hard when you have remote branches (I have to remove the remote branch, and recreate it after the rebase ).
We just went to one master branch, with feature branches, or sprint branches being PR-ed into it. The key is that there are no long lived branches outside the master branch.

How do you deal with this issue?

**Comment by xavier-morera** [comment]
@gjunge thanks for your time

To answer your questions:
- Yes, convert-unit-tests-xunit goes to Develop now
- Async branch to Develop as well
- I have it in my to do list to do the nuspec files, but I have not done it before so if you can, branch from Develop and then...

We can release a new version with these three branches and this one can go to Nuget now. 

I know I am complicating things a bit but there is a lot of things that we need to catch on and I believed in having one last release with MBUnit + new .NET before moving forward. There are many PRs pending and Solr is already aiming for version 7 soon, and there are many features that are not yet supported. 

Regarding GitFlow, I know there are strong arguments against it (but also to use them) and so the two long lived branches work well when Master is always production ready while Develop is work in progress. I haven't had any problems in the teams that I have worked with that use it, agreed it is not totally tidy but it is something that many people are aware so it is not necessary to explain the process if we went for a different method.  It is different in a team that is used to work together than in an open source project.

IMHO: Let's do this, let's use Gitflow for now and see if we have noticeable issues, and if we do we can talk about other possibilities. 

What do you think?

**Comment by gjunge** [comment]
I agree to let's use GitFlow for now, I understand that you understand the pros and cons, so now it is just really just to see how it goes in practical terms. 

I created a PR for the xunit branch into dev, if you could just merge it, then I can tomorrow find some time to make the nuspecs. 

Regarding NuGet, to confirm: 
- version 0.7.1
- creator Mauricio Scheffer
- authors: Mauricio Scheffer, Xavier Morera and contributors
(Added your name as author)

**Comment by xavier-morera** [comment]
@gjunge thanks but I will remove my name. Let's leave only Mauricio for now as he did a ton of work and I don't want to take any credit away for him.  I am just helping get the project get back on track and not even close on the amount of work that you have done. I will add your name and mine to contributors section in documentation.

PR merged too. Thanks.

**Pull request merged**
