### PR TITLE
Convert all test to xUnit

### PR DESCRIPTION
**Pull request by gjunge**
See #289 

- [x] All tests migrated
- [x] Created integration test runner `run-integrationtests`: starts solr and runs all Integration tests. Alternatively, one can run solr, and then run the Integration tests in the IDE
- [x] Removed tests from FAKE.

Note:
* Not all integration tests work, they also didn't seem to work in the past. This is something we should fix when moving to solr 6.6
* nHibernate tests don't run well on AppVeyor, probably should migrate nHibernate to a different repository because it is deprecated. 
image

[Build status](https://ci.appveyor.com/project/gjunge/solrnet)

### CODE REVIEW

**Comment by xavier-morera** [comment]
@gjunge great work! I just need to resolve a couple of conflicts here and do one last test and then will start the release process for this package.

Then the next step would be to update in Nuget.

**Comment by gjunge** [comment]
If you have question regarding the conflicts, let me know, they seem to be not very complicated.

**Comment by xavier-morera** [comment]
Agreed. Just that I have a hard deadline for today on a presentation that I need to meet and then will get to this.

**Comment by xavier-morera** [comment]
@gjunge I just merged net-update-plus-autofac-ninject into develop to do a release, but will not include this change just yet to do one last release for those using the project that still rely on MBUnit. But immediately as I do the release, I will merge this into a new feature branch and will also work on Nuget. BTW: really good work, thank you.

**Pull request merged**
