### PR TITLE
Add netstandard 2.0 support for SolrNet.Cloud

### PR DESCRIPTION
**Pull request by gjunge**
* Moved from ZookeeperNet to ZookeeperNetEx
* Made Init of SolrCloudStateProvider async
* Bumped versions to 0.8.1

I kind of worked blindely, has to be tested by somebody that has a SolrCloud setup.
The Dispose method of SolrCloudStateProvider currently contains an non-awaited async call, which is don't really like, but currently have no other solution.

### CODE REVIEW

**Comment by xavier-morera** [comment]
@gjunge  I may be able to test with a large SolrCloud deployment. I had a talk yesterday with the folks with whom I built the search API for an enterprise application. I will find out more in the next couple of days. It is currently in 4.10.3, but they are working on moving to 6.x

**Comment by gjunge** [comment]
@xavier-morera  That would be great. Would also be nice to have our Docker thing running.

Btw, other subject, there are tons of issues and prs that can be closed, do you want me to reference them to the PR's that closed them so we have it documented, and then you can close them.

**Comment by xavier-morera** [comment]
@gjunge It is a decent sized application, with multiple SolrCloud environments, about 80k users and there are many testers so it will be a thorough test. I left the project a month a few months ago so I can't do it myself, but if they are ok I can collaborate and review.

If you can reference the PRs that can be closed, I will proceed. Thanks (again)

**Comment by gjunge** [comment]
@xavier-morera  Most of these issues where are connected to some PR , and all of them are irrelevant
(I don't want to reference them to this PR , it wouldn't make sense)
289 
283
279
272
271
269
264
256
217
175
91
86

These pull requests can be closed:
187
186
144

**Comment by xavier-morera** [comment]
Done.  @gjunge (again thanks)

**Pull request merged**
