### PR TITLE
Upgrade to new csproj format and simplify nuget creation

### PR DESCRIPTION
**Pull request by gjunge**
I've upgraded all projects to the new lean csproj format, according to http://www.natemcmaster.com/blog/2017/03/09/vs2015-to-vs2017-upgrade/ tips.

This enabled us to have the `csproj` file define the NuGet package specification, allowing us to remove the `nuspec` files.

Overall we got rid of:
 - *.nuspec
 - packages.config
 - binding redirects in app.config (and also many app.config files)
 - redundant references (https://docs.microsoft.com/en-us/nuget/consume-packages/dependency-resolution). Since `ApplicationReference` s are transitive, we don't have to include their dependencies anymore.

In addition the move to netstandard 2.0 will be super easy, once all dependency of a certain project support netstandard 2.0, we just have to change
``` xml
<TargetFramework>net46</TargetFramework>
```
to
``` xml
<TargetFrameworks>net46;netstandard2.0</TargetFrameworks>
```

### CODE REVIEW

**Comment by xavier-morera** [comment]
@gjunge great! I am traveling today, will release once I get back tonight

**Comment by PaulStupka** [comment]
Hello @gjunge 
Could you please share the reason for removing the HttpRuntimeCache class in the scope of this PR?

**Comment by gjunge** [comment]
I believe that we wanted to remove dependency on System.Web so porting to .net standard would be possible. I also believe that it wasn’t in use, though I’m not sure about that. 
Do you need this feature?

**Comment by PaulStupka** [comment]
Thank you @gjunge 
Sitecore was using this implementation.
I believe there should be no difficulties to create its own implementation.
Cheers!

**Pull request merged**
